services:
  code_server:
    build:
      context: .
      args:
        - YOUR_UID=${YOUR_UID}
        - YOUR_GID=${YOUR_GID}
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    expose:
      - 8000
    restart: always
networks:
  default:
    name: nginx-network
    external: true