version: '3'
services:
  code_server:
    build:
      context: .
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${CODE_PORT}:8080
    volumes:
      - ${HOME}:/home/ubuntu/@HOST_HOME