#!/bin/bash

# EXPORT VARIABLE(S)
read -p "PROJECT_NAME: " PROJECT_NAME
read -p "VIRTUAL_HOST: " VIRTUAL_HOST
read -p "LETSENCRYPT_EMAIL: " LETSENCRYPT_EMAIL
export PROJECT_NAME VIRTUAL_HOST LETSENCRYPT_EMAIL

# RUN DOCKER-COMPOSE
docker-compose build --no-cache
docker-compose -p ${PROJECT_NAME} up -d