services:
  jupyter:
    build:
      context: .
      args:
        - BASE_IMAGE_NAME=${BASE_IMAGE_NAME}
        - YOUR_UID=${YOUR_UID}
        - YOUR_GID=${YOUR_GID}
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${JUPYTER_PORT}:8888
    volumes:
      - ${HOME}:/home/jupyter/@HOST_HOME
      - ${HOME}/.jupyter:/home/jupyter/.jupyter
      - ./user-settings:/home/jupyter/.jupyter/lab/user-settings
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
