version: '3'

services:
  wp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - YOUR_UID=${YOUR_UID}
    image: ${YOUR_UID}/wordpress:latest
    container_name: ${CONTAINER_NAME}
    volumes:
      - ${WORDPRESS_PATH}:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db-mysql:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      VIRTUAL_HOST: ${DOMAIN_NAME_LIST}
      LETSENCRYPT_HOST: ${DOMAIN_NAME_LIST}
      LETSENCRYPT_EMAIL: ${EMAIL_ADDRESS}
    networks:
      - nginx-network
      - mysql-network

networks:
  nginx-network:
    external: true
    name: nginx-network
  mysql-network:
    external: true
    name: mysql-network