services:
  nginx-bridge:
    image: nginx
    container_name: ${CONTAINER_NAME}
    environment:
      NETWORK_ACCESS: internal
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - ./localhost.conf:/etc/nginx/conf.d/localhost.conf
    restart: always
    networks:
      - nginx-network
networks:
  nginx-network:
    external: true
